### ISSUE TITLE
与最新版的vconsole已经不兼容了

### ISSUE THREAD

**Issue by liweitian** [sunlanda/vconsole-outputlog-plugin#1]

**Comment by ARuanLY** [comment]
个人写了支持最新版的vConsole v3.15.1的[vconsole-exportlog-plugin](https://www.npmjs.com/package/vconsole-exportlog-plugin)，欢迎使用

vconsole-exportlog-plugin
===

A [vConsole](https://github.com/Tencent/vConsole) plugin for copying logs and exporting logs to a file.

Support vConsole v3.15.1.

---

## Features

- Copy logs to the clipboard
- Export logs as a local file
- Filter logs by type before copying or exporting

## Installation

```bash
npm i vconsole-exportlog-plugin
```

## Usage

```ts
import VConsole from 'vconsole'
import VConsoleExportLogsPlugin from 'vconsole-exportlog-plugin'

const vConsole = new VConsole()
new VConsoleExportLogsPlugin(vConsole)
```

<img width="1363" height="816" alt="Image" src="https://github.com/user-attachments/assets/053c86b6-202f-4546-af8e-b3b80e1c4b48" />
